FORMAT: 1A

# WARM API（业务系统API）
此分类下的API主要是给IM客户端调用，以完成产品业务，以所也可以称为**业务系统API**，以便与**IM系统API**区分开来。**业务系统API**同时也是IM客户端连接到IM服务端的**介绍人**，因为IM客户端必须依赖**业务系统API**提供的token才能使用**IM系统API**。

## 基本信息

+ 版本：v1
+ 定义时间：2019-12-16
+ 应用时间：2019-03-16

## 基本约定

+ URL前缀：/api/v1/
+ 接口形态：Restful
+ 方法：GET/POST/PUT/DELETE
+ 返回：JSON

## HTTP请求头

+ 需要验证的操作: **Authorization：JWT jwt-token**

## http响应格式
+ Attributes (object)

    + code: 0 (number, required) -  系统状态码
    + message: error (string, required) - 错误信息 
    + data: {} (object), required) -  响应数据


+ Body
    {
        "code": 0,
        "message": "error",
        "data": {...},
    }

// ## http状态码定义
// + 200：GET、PUT、PATCH success
// + 201：POST success
// + 204：DELETE success
// + 400：bad request, bad param
// + 401：api unauthorized
// + 403：user forbidden
// + 404：GET not found


## 平台启动信息 /config/{platform} [/config/{platform}]
### 平台启动信息 [GET]
+ Parameters
    + platform: iphone (string, required) - 平台： pc iphone android mac

+ Response  200 (application/json)
    + Attributes (object)

        + start_info:  (object, required) - 启动信息
            + start_type: picture (string, required) - 启动类型
            + picture_url: /xxx/xxx (string, required) - 启动图片地址
            + video_url: /xxx/xxx (string, required) - 启动视频地址
        + version_info: (object, required) - 版本信息
            + updated_at: 2020-01-13 13:49:00 (string, required) -  更新发布时间
            + platform:  iphone (string, required) - 平台： pc iphone android mac
            + ver: 0.0.1 (string, required) - 版本号
            + downloa_url: http://xxx.xxx.com (string, required) -  下载地址
            + upgrade_info: upgrade: 1.xxxx; (string, required) - 版本更新信息
            + is_force: true (string,required) - 是否强制更新
        + web_server: (object, required) - http服务器
            + addrs: ["1270.0.0.1:9001"] (array, required) - http服务器地址
        + file_server: (object, required) - 文件服务
            + addrs: ["1270.0.0.1:9001"] (array, required) - 文件服务地址

    + Body
        {
            "start_info": {
                "start_type": "picture",
                "picture_url": "/xxx/xxx",
                "video_url": "/xxx/xxx"
            },
            "version_info": {
                "updated_at": "2020",
                "platform": "iphone",
                "ver": "0.0.1",
                "downloa_url": "http://xxx.xxx.com",
                "upgrade_info": "upgrade: 1.xxxx;",
                "is_force": "true"
            },
            "web_server": {
                "addrs": [
                "[\"1270.0.0.1:9001\"]"
                ]
            },
            "file_server": {
                "addrs": [
                "[\"1270.0.0.1:9001\"]"
                ]
            }
        }

## 系统时间 /system/time [/system/time]
### 获取系统时间[GET]

+ Response  200 (application/json)
    + Attributes (object)
        + time: 150000000 (number, required) -  系统时间戳

## SMS短信 /sms/{phone} [/sms/{phone}]
### 发送短信 [POST]
+ Parameters
    + phone: 10086 (string, required) - 手机号码

+ Request (application/json)
    + Attributes (object)
        + country_code: +86 (string, required) - 国家号
        + sms_type: vcode (string, required) - 短信类型
        + is_test: 0 (number, required) - 是否测试

+ Response 201 (application/json)
    + Attributes (object)
        + v_code: 7835 (string, required) - 验证码(测试环境才会返回验证码)
        + expire：60 (number, required) - 有效期(second)
    + Body
        {
            "v_code": "7835",
            "expire": 60,
        }


## auth /auth/ [/auth/]
### login [POST]
+ Request (application/json)
    + Attributes (object)
        + v_code: 0988 (string, optional) - 登录验证码
        + pwd： passwordxxxxx (string, optional) - 登录密码
        + platform: iphone (string, required) - 设备类型：android、iphone、pc、mac
        + country_code: +86 (string, required) - 国家号
        + login_type: vcode (string, required) - 登录类型: vcode/pwd
        + phone: 10086 (string, required) - 手机号码
        + device (object)
            + name: HUAWEI (string, required) - 设备名称
            + model: android xxx (string, required) - 设备型号
            + mac：jsldfjl (string, required) - 设备mac地址
            + version： v0.0.1 (string, required) - 系统版本

+ Response 201 (application/json)
    + Attributes (object)    
        + web_server: (object, required) - http服务器
            + addrs: ["1270.0.0.1:9001"] (array, required) - http服务器地址
        + file_server: (object, required) - 文件服务器
            + addrs: ["1270.0.0.1:9001"] (array, required) - 文件服务地址
        + im_server: (object, required) - im服务器
            + addrs: ["1270.0.0.1:9001"] (array, required) - im服务地址
        + user: (object, required)
            + user_id: 
        + token: xxxxxxxxx (array, required) - token
        + exp: 60 (array, required) - token
        + im_token: xxxxxxxxx (array, required) - im token
        + im_exp: 40 (array, required) - im token exp


### logout [DELETE]
+ Response 204 (application/json)


## 二维码登陆相关 /auth/qrcode [/auth/qrcode{?qr_token}]
### 获取二维码状态（pc接口) [GET]
+ Parameters
    + qr_token: xxxx (string, required) - qrCode token
+ Response 200 (application/json)

### 创建登陆二维码（pc接口） [POST]

+ Request (application/json)
    + Attributes (object)
        + platform: pc (string, required) - 设备类型
        + name: HUAWEI (string, required) - 设备名称
        + model: android xxx (string, required) - 设备型号
        + mac：jsldfjl (string, required) - 设备mac地址
        + version： v0.0.1 (string, required) - 系统版本

+ Response 201 (application/json)

    + Attributes (object)

### app扫码登陆、 同意/取消二维码登陆 （app接口） [PATCH]
+ Request (application/json)

    + Attributes (object)

        + qr_token: xxxxx (string, required) - qr_token
        + update_type: scan_code (string, required) -  操作类型：scan_code/agree/cancel

+ Response 200 (application/json)



## 通过phone搜索联系人 /user/phone/{phone} [/users/phone/{phone}]
### 通过phone搜索联系人parameters [GET]
+ Parameters
    + phone: xxxxx (string, required) - 手机号

+ Response 200 (application/json)
    + Attributes (object)
        + users: (array, required) - 用户列表 
            + user (object)
                + user_id: 125 (number, required) - 用户id
                + account: xxxxx (string, required) - 账号
                + account_alias: xxxxx (string, required) - 账号别名
                + im_id: 125 (number, required) - im id
                + nickname: xxxxx (string, required) - 用户昵称
                + platform: xxxxx (string, required) - 设备平台
                + country_code: xxxxx (string, required) - 国家号
                + phone: xxxxx (string, required) - 手机号
                + home_phone: xxxxx (string, required) - 座机号码
                + sex: xxxxx (string, required) - 性别: 男：male， 女：female
                + birthday: xxxxx (string, required) - 生日： 19xx-xx-xx
                + avatar: xxxxx (string, required) - /image/avatar/1.png
                + job: xxxxx (string, required) - 用户工作
                + address: xxxxx (string, required) - 用户地址
                + signature: xxxxx (string, required) - 个性签名
    
    + Body
    {
        "users": [
            {
                "user_id": 1,
                "account": "A1NSHijF6cBpudF3khcBCkfmVm",
                "account_alias": "",
                "im_id": 0,
                "nickname": "ujtb4h",
                "platform": "iphone",
                "country_code": "+86",
                "phone": "18814181870",
                "home_phone": "",
                "sex": "",
                "birthday": "",
                "avatar": "/image/avatar/5.jpeg",
                "email": "",
                "job": "",
                "address": "",
                "signature": "hello world!"
            }
        ]
    }

## 通过account搜索联系人 /user/account/{account} [/users/account/{account}]
### 通过account搜索联系人 [GET]
+ Parameters
    + account: xxxxx (string, required) - 账号

+ Response 200 (application/json)
    + Attributes (object)
        + users: (array, required) - 用户列表 
            + user (object)
                + user_id: 125 (number, required) - 用户id
                + account: xxxxx (string, required) - 账号
                + account_alias: xxxxx (string, required) - 账号别名
                + im_id: 125 (number, required) - im id
                + nickname: xxxxx (string, required) - 用户昵称
                + platform: xxxxx (string, required) - 设备平台
                + country_code: xxxxx (string, required) - 国家号
                + phone: xxxxx (string, required) - 手机号
                + home_phone: xxxxx (string, required) - 座机号码
                + sex: xxxxx (string, required) - 性别: 男：male， 女：female
                + birthday: xxxxx (string, required) - 生日： 19xx-xx-xx
                + avatar: xxxxx (string, required) - /image/avatar/1.png
                + job: xxxxx (string, required) - 用户工作
                + address: xxxxx (string, required) - 用户地址
                + signature: xxxxx (string, required) - 个性签名
    
    + Body
    {
        "users": [
            {
                "user_id": 1,
                "account": "A1NSHijF6cBpudF3khcBCkfmVm",
                "account_alias": "",
                "im_id": 0,
                "nickname": "ujtb4h",
                "platform": "iphone",
                "country_code": "+86",
                "phone": "18814181870",
                "home_phone": "",
                "sex": "",
                "birthday": "",
                "avatar": "/image/avatar/5.jpeg",
                "email": "",
                "job": "",
                "address": "",
                "signature": "hello world!"
            }
        ]
    }

## 通过id搜索联系人 /user/id/{id} [/users/id/{id}]
### 通过id搜索联系人 [GET]
+ Parameters
    + id: 4524 (number, required) - 用户id

+ Response 200 (application/json)
    + Attributes (object)
        + contacts: (array, required) - 用户列表 
            + contact (object)
                + user_id: 125 (string, required) - 用户id
                + account: xxxxx (string, required) - 账号
                + account_alias: xxxxx (string, required) - 账号别名
                + im_id: 125 (string, required) - im id
                + nickname: xxxxx (string, required) - 用户昵称
                + platform: xxxxx (string, required) - 设备平台
                + country_code: xxxxx (string, required) - 国家号
                + phone: xxxxx (string, required) - 手机号
                + home_phone: xxxxx (string, required) - 座机号码
                + sex: xxxxx (string, required) - 性别: 男：male， 女：female
                + birthday: xxxxx (string, required) - 生日： 19xx-xx-xx
                + avatar: xxxxx (string, required) - /image/avatar/1.png
                + job: xxxxx (string, required) - 用户工作
                + address: xxxxx (string, required) - 用户地址
                + signature: xxxxx (string, required) - 个性签名
    
    + Body
    {
        "contacts": [
            {
                "user_id": 1,
                "account": "A1NSHijF6cBpudF3khcBCkfmVm",
                "account_alias": "",
                "im_id": 0,
                "nickname": "ujtb4h",
                "platform": "iphone",
                "country_code": "+86",
                "phone": "18814181870",
                "home_phone": "",
                "sex": "",
                "birthday": "",
                "avatar": "/image/avatar/5.jpeg",
                "email": "",
                "job": "",
                "address": "",
                "signature": "hello world!"
            }
        ]
    }


## 联系人集合 /users/{id}/contacts [/users/{id}/contacts]
### 获取所有联系人的信息 [GET]

+ Parameters
    + id: 1235 (number, required) - 用户id

+ Response  200 (application/json)

    + Attributes (object)
        + contacts: (array, required)
            + contact (object)
                + user_id: 86 (number, required) - 用户id
                + nickname: neil (string, required) - 昵称
                + friend_nickname: neil (string, required) - 用户对朋友的昵称 
                + avatar: /image/avatar/2.png (string, required) - 最后更新时间
                + im_id: 137 (number, required) - im id
                + mute_notice: yes (string, required) - 消息免打扰： yes/no. 默认：no

    + Body
        {
            "contacts": [
                {
                    "user_id": 100000135,
                    "im_id": 0,
                    "nickname": "ujtb4h",
                    "friend_nickname": "",
                    "avatar": "/image/avatar/5.jpeg",
                },
                {
                    "user_id": 100000136,
                    "im_id": 0,
                    "nickname": "ujtb4h",
                    "friend_nickname": "",
                    "avatar": "/image/avatar/5.jpeg",
                },
                {
                    "user_id": 100000138,
                    "im_id": 0,
                    "nickname": "ujtb4h",
                    "friend_nickname": "",
                    "avatar": "/image/avatar/5.jpeg",
                },
                {
                    "user_id": 100000137,
                    "im_id": 0,
                    "nickname": "ujtb4h",
                    "friend_nickname": "",
                    "avatar": "/image/avatar/5.jpeg",
                }
            ]
        }

## 联系人信息 /users/{id}/contacts/{cid}  [/users/{id}/contacts/{cid}]
### 获取单个联系人信息 [GET]
+ Parameters
    + id: 1235 (number, required) - 用户id
    + cid: 1235 (number, required) - 联系人id

+ Response  200 (application/json)

    + Attributes (object)
        + user_id: 125 (string, required) - 用户id
        + account: xxxxx (string, required) - 账号
        + account_alias: xxxxx (string, required) - 账号别名
        + im_id: 125 (string, required) - im id
        + nickname: xxxxx (string, required) - 用户昵称
        + platform: xxxxx (string, required) - 设备平台
        + country_code: xxxxx (string, required) - 国家号
        + phone: xxxxx (string, required) - 手机号
        + home_phone: xxxxx (string, required) - 座机号码
        + sex: xxxxx (string, required) - 性别: 男：male， 女：female
        + birthday: xxxxx (string, required) - 生日： 19xx-xx-xx
        + avatar: xxxxx (string, required) - /image/avatar/1.png
        + job: xxxxx (string, required) - 用户工作
        + address: xxxxx (string, required) - 用户地址
        + signature: xxxxx (string, required) - 个性签名
        + is_friend: true (string , required) - 是否是朋友，布尔值
        + is_delete: false (string , required) - 是否是朋友，布尔值
        + is_black: false (string , required) - 是否是朋友，布尔值
        + friend_nickname: derek (string, required) - 对朋友的昵称
        + add_by: share (string, required) - 联系人的添加方式：share/scan/phone/account

### 添加联系人,同意/拒绝添加联系人 [POST]
+ Parameters
    + id: 1235 (number, required) - 用户id
    + cid: 1235 (number, required) - 联系人id

+ Request (application/json)

    + Attributes (object)
        + handle_type: add (string, required) - 处理类型：add/agree/reject
        + add_by: share (string, optional) - 通过什么方式添加朋友：share/scan/phone/account
        + message: I'm xx (string, optional) - 添加朋友时的备注
        + friend_im_id: 243 (number, required) - 联系人imid

+ Response  201 (application/json)

    + Attributes (object)

### 修改联系人信息 [PATCH]
+ Parameters
    + id: 1235 (number, required) - 用户id
    + cid: 1235 (number, required) - 联系人id

+ Request (application/json)
    + Attributes (object)
        + nickname: derek (string, required) - 用户昵称


+ Response  200 (application/json)


### 删除联系人 [DELETE]
+ Parameters
    + id: 1235 (number, required) - 用户id
    + cid: 1235 (number, required) - 联系人id

+ Response  204 (application/json)


## 个人中心 /users/{user_id} [/users/{user_id}]
### 获取个人中心信息 [GET]
+ Parameters
    + id: 1235 (number, required) - 用户id 

+ Response  200 (application/json)

    + Attributes (object)
        + user_id: 125 (string, required) - 用户id
        + account: xxxxx (string, required) - 账号
        + account_alias: xxxxx (string, required) - 账号别名
        + im_id: 125 (string, required) - im id
        + nickname: xxxxx (string, required) - 用户昵称
        + platform: xxxxx (string, required) - 设备平台
        + country_code: xxxxx (string, required) - 国家号
        + phone: xxxxx (string, required) - 手机号
        + home_phone: xxxxx (string, required) - 座机号码
        + sex: xxxxx (string, required) - 性别: 男：male， 女：female
        + birthday: xxxxx (string, required) - 生日： 19xx-xx-xx
        + avatar: xxxxx (string, required) - /image/avatar/1.png
        + job: xxxxx (string, required) - 用户工作
        + address: xxxxx (string, required) - 用户地址
        + zone: xxxxx (string, required) - 地区
        + signature: xxxxx (string, required) - 个性签名
        + password: true (number, required) -  布尔值，是否已设置密码

### 修改个人中心信息 [POST]
+ Parameters
    + id: 1235 (number, required) - 用户id

+ Request (application/json)
    + Attributes (object)
        + nickname: derek (string, required) - 要修改的昵称
        + signature: yes (string, required) - 个性签名
        + avatar： kdflsjfl13515ajsdf (string, required) - 头像的file token
        + sex: xxxxx (string, required) - 性别: 男：male， 女：female
        + birthday: xxxxx (string, required) - 生日： 19xx-xx-xx
        + zone: xxxxx (string, required) - 地区
        + address: xxxxx (string, required) - 用户地址

+ Response  200 (application/json)

## 文件上传 /files [/files]
### 上传文件 [POST]
form的命名统一为file
+ Headers:

    + file: name.txt (string, required) - 文件名
    + content-type: multipart/form-data; (string, required) - 内容类型

+ Response 200 (application/json)

    + file_token: asdfasdgagas (string, required) - 文件token


## 下载文件 /files/{file_token} [/files/{file_token}]
### 下载文件 [GET]
+ Parameters
    + file_token: werutipoiqeutoijqoeij (string, required) - 文件token

+ Response 200 ()
    + Attributes (object)


## 群相关操作 /groups [/groups]
### 创建群（Y） [POST]

+ Request (application/json)

    + Attributes (object)
        + user_ids (array, required) - 用户id数组，
            + id : 123 (number) - 用户id
        + name: my group (string, required) - 群名称
        + group_type: chat (string, optional) - 群类型
        + max_cap: 100 (number, optional) - 群成员容量，默认200
        + notice: hello world! (string, optional) - 群通告

+ Response 200 (application/json)

    + Attributes (object)
        + group_id: 123 (number, required) - 群id
        + name: my group (string, required) - 群名称
        + group_type: chat (string, required) - 群类型
        + max_cap: 100 (number, required) - 群成员容量，默认200
        + member_hash: lkajslkdjfla (string, required) - 成员hash： 所有群成员的id按升序排列，合并成一个字符串，再计算该字符串的md5
        + created_at: 15xxxxx (number,required) - 建群时间
        + owner_id: 1 (number, required) - 群主的用户id
        + creator_id: 1 (number, required) - 建群者的用户id
        + avatar: /image/avatar/2.png (string, required) - 群头像，暂时先分配默认头像
        + notice: hello world! (string, required) - 群通告

### 获取群列表(Y) [GET]

+ Response 200 (application/json)

    + Attributes (object)
        + group_id: 123 (number, required) - 群id
        + name: my group (string, required) - 群名称
        + avatar: /image/avatar/2.png (string, required) - 群头像，默认空值
        + count: 1 (number, required) - 群成员人数
        + role： owner (string, required) - 群角色： owner/admin/member
        + mute_notice: yes (string, required) - 消息免打扰： yes/no

## 获取群信息 /groups/{group_id}/info [/groups/{group_id}/info]
### 获取群概要信息(Y)  [GET]
+ Parameters
    + group_id: 1235 (number, required) - 群id

+ Response 200 (application/json)

    + Attributes (object)
        + group_id: 123 (number, required) - 群id
        + name: my group (string, required) - 群名称
        + group_type: chat (string, required) - 群类型
        + max_cap: 100 (number, required) - 群成员容量，默认200
        + member_hash: lkajslkdjfla (string, required) - 成员hash
        + created_at: 15xxxxx (number,required) - 建群时间
        + owner_id: 1 (number, required) - 群主的用户id
        + creator_id: 1 (number, required) - 建群者的用户id
        + avatar: /image/avatar/2.png (string, required) - 群头像，暂时先分配默认头像
        + notice: hello world! (string, required) - 群通告


## 群操作 /groups/{group_id} [/groups/{group_id}]
### 获取完整群信息(Y)  [GET]
+ Parameters
    + group_id: 1235 (number, required) - 群id

+ Response 200 (application/json)

    + Attributes (object)
        + info (object) - 群信息
            + group_id: 123 (number, required) - 群id
            + name: my group (string, required) - 群名称
            + group_type: chat (string, required) - 群类型
            + max_cap: 100 (number, required) - 群成员容量，默认200
            + member_hash: lkajslkdjfla (string, required) - 成员hash
            + created_at: 15xxxxx (number,required) - 建群时间
            + owner_id: 1 (number, required) - 群主的用户id
            + creator_id: 1 (number, required) - 建群者的用户id
            + avatar: /image/avatar/2.png (string, required) - 群头像，暂时先分配默认头像
            + notice: hello world! (string, required) - 群通告
        + notice (object) - 群公告
            + notice_id: 12435 (number, required) - 群公告id
            + notice: hello world! (string, required) - 群公告信息
            + updated_at: 15xxxxxxxx (number, required) -  更新时间戳
            + modify_by: 12435 (number, required) - 更新者用户id
        + settings (object) - 群设置
            + no_speaking: 123 (number, required) - 禁言, 0: 关闭， 1：开启
            + add_in_group: 1 (string, required) - 允许群内添加好友, 0: 关闭， 1：开启
            + invite: 1 (string, required) - 允许邀请人入群, 0: 关闭， 1：开启
            + invite_way: 1 (number, required) - 邀请人入群方法, ...
        + roles (array) - 群角色列表
            + roles (object)
                + user_id: 1 (number, required) - 用户id
                + role: admin (string, required) - 群角色： owner/admin/member
                + no_speaking: 1 (number, required) - 是否有禁言权力, 0: 开启，1： 关闭
                + modify_info: 1 (number, required) - 是否有修改群信息的权力, 0: 开启，1： 关闭
                + add_in_group: 1 (number, required) - 是否能设置群内添加好友的能力, 0: 开启，1： 关闭
        + members (array) - 成员列表
            + members (object)
                + group_nickname: derek (string, required) - 用户昵称
                + user_id: 123 (number, required) - 用户id
                + imid: 1241235 (number, required) - imid
                + avatar: /image/avatar/2.png  (string, required) - 用户头像
        + member_settings (array) - 成员设置
            + member_settings (object) 
                + user_id: 123 (number, required) - 用户id
                + no_speaking: 15xxxxx (number, required) - 禁言结束时间戳

    + Body 
    {
        "info": {
            "group_id": 22,
            "name": "sg1zs3、ginsx4、c3n3fw",
            "create_at": 1582874658,
            "update_at": 1582874658,
            "group_type": "chat",
            "max_cap": 200,
            "avatar": "5ce1170cab0a083b91d09a1b0cfb8d0a",
            "notice": "",
            "creator_id": 16,
            "owner_id": 16,
            "member_hash": "9758095553d254459482bd606612cf84"
        },
        "notice": {
            "notice_id": 0,
            "notice": "",
            "updated_at": -62135596800,
            "modify_by": 0
        },
        "settings": {
            "no_speaking": 0,
            "add_in_group": 1,
            "invite": 0,
            "invite_way": 1
        },
        "roles": [
            {
                "user_id": 16,
                "role": "owner",
                "no_speaking": 1,
                "modify_info": 1,
                "add_in_group": 1
            },
            {
                "user_id": 18,
                "role": "member",
                "no_speaking": 0,
                "modify_info": 0,
                "add_in_group": 0
            },
            {
                "user_id": 24,
                "role": "member",
                "no_speaking": 0,
                "modify_info": 0,
                "add_in_group": 0
            }
        ],
        "members": [
            {
                "user_id": 16,
                "im_id": 1582799689503524,
                "group_nickname": "sg1zs3",
                "avatar": "3ee76fabaec2bf385015049390210f45",
                "role": ""
            },
            {
                "user_id": 18,
                "im_id": 1582800854198274,
                "group_nickname": "ginsx4",
                "avatar": "b4db9c634ca0a753ac1edc0f23f3b4ad",
                "role": ""
            },
            {
                "user_id": 24,
                "im_id": 1582859137417914,
                "group_nickname": "c3n3fw",
                "avatar": "b4db9c634ca0a753ac1edc0f23f3b4ad",
                "role": ""
            }
        ],
        "member_settings": [
            {
                "user_id": 16,
                "no_speaking": 0
            },
            {
                "user_id": 18,
                "no_speaking": 0
            },
            {
                "user_id": 24,
                "no_speaking": 0
            }
        ]
    }

### 修改群信息(Y)  [POST]
+ Request (application/json)
    + Attributes (object)
        + name: my group (string, optional) - 群名称
        + owner_id: 1 (number, optional) - 群主的用户id
        + max_cap: 100 (number, optional) - 群成员容量，默认200
        + avatar: /image/avatar/2.png (string, optional) - 群头像，暂时先分配默认头像
        + notice: hello world! (string, optional) - 群通告

+ Response 200 (application/json)
    + Attributes (object)

### 解散群(Y)  [DELETE]
+ Parameters
    + group_id: 1235 (number, required) - 群id

+ Response 200 (application/json)
     + Attributes (object)


## 群成员 /groups/{group_id}/members [/groups/{group_id}/members]
### 获取群成员列表(Y) [GET]
+ Parameters
    + group_id: 1235 (number, required) - 群id

+ Response 200 (application/json)
    + Attributes (object)
        + member_hash: asldkjflaksjdfl (string, required) - 群成员hash
        + members: (array, require) - 数组
            + members (object)
                + group_nickname: derek (string, required) - 用户昵称
                + user_id: 123 (number, required) - 用户id
                + imid: 1241235 (number, required) - imid
                + avatar: /image/avatar/2.png  (string, required) - 用户头像
                + role: owner (string, required) - 用户群角色

### 添加群成员(Y) [POST]
+ Parameters
    + group_id: 1235 (number, required) - 群id

+ Request (application/json)
    + Attributes (object)
        + user_ids (array, required) - 用户id数组，
            + id : 123 (number) - 用户id


+ Response 200 (application/json)
    + Attributes (object)

### 移除群成员(Y) [DELETE]
+ Parameters
    + group_id: 1235 (number, required) - 群id

+ Request (application/json)
    + Attributes (object)
        + user_ids (array, required) - 用户id数组，
            + id : 123 (number) - 用户id

+ Response 200 (application/json)
    + Attributes (object)

## 群成员 /groups/{group_id}/members/{user_id} [/groups/{group_id}/members/{user_id}]
### 获取群成员信息(Y) [GET]
+ Parameters
    + group_id: 12 (number, required) - 群id
    + user_id: 1235 (number, required) - 用户id

+ Response 200 (application/json)
    + Attributes (object)
        + user_id: 125 (string, required) - 用户id
        + account: xxxxx (string, required) - 账号
        + account_alias: xxxxx (string, required) - 账号别名
        + im_id: 125 (string, required) - im id
        + nickname: xxxxx (string, required) - 用户昵称
        + platform: xxxxx (string, required) - 设备平台
        + country_code: xxxxx (string, required) - 国家号
        + phone: xxxxx (string, required) - 手机号
        + home_phone: xxxxx (string, required) - 座机号码
        + sex: xxxxx (string, required) - 性别: 男：male， 女：female
        + birthday: xxxxx (string, required) - 生日： 19xx-xx-xx
        + avatar: xxxxx (string, required) - /image/avatar/1.png
        + job: xxxxx (string, required) - 用户工作
        + address: xxxxx (string, required) - 用户地址
        + signature: xxxxx (string, required) - 个性签名
        + role: owner (string, required) - 群角色
        + group_nickname: derek (string, required) - 群昵称

### 修改群成员信息(Y) [POST]
+ Parameters
    + group_id: 12 (number, required) - 群id
    + user_id: 1235 (number, required) - 用户id

+ Request (application/json)
    + Attributes (object)
        + group_nickname: derek (string, required) - 群成员的昵称

+ Response 200 (application/json)
    + Attributes (object)

### 群成员退群(Y) [DELETE]
+ Parameters
    + group_id: 12 (number, required) - 群id
    + user_id: 1235 (number, required) - 用户id

+ Response (application/json)
    + Attributes (object)


## 群成员设置 /groups/{group_id}/members/{user_id}/settings [/groups/{group_id}/members/{user_id}/settings]
### 获取群成员设置 [GET]
+ Parameters
    + group_id: 12 (number, required) - 群id
    + user_id: 1235 (number, required) - 用户id

+ Response 200 (application/json)
    + Attributes (object)
        + setting：(object)
            + user_id: 123 (number, required) - 用户id
            + no_speaking: 15xxxxx (number, required) - 禁言结束时间戳

### 修改群成员设置 [POST]
+ Parameters
    + group_id: 12 (number, required) - 群id
    + user_id: 1235 (number, required) - 用户id

+ Request (application/json)
    + Attributes (object)
        + type: 1 (number, required) - 类型，暂时为1
        + key: no_speaking (string, required) - 设置类型， no_speaking:禁言
        + value: 1 (number, required) - 设置值， no_speaking：禁言结束时间戳

+ Response 200 (application/json)
    + Attributes (object)

## 群设置 /groups/{group_id}/settings [/groups/{group_id}/settings]
### 获取群设置 [GET]
+ Parameters
     + group_id: 12 (number, required) - 群id
+ Response 200 (application/json)
    + Attributes (object)
        + setting (object) - 新增的群列表信息
            + no_speaking: 123 (number, required) - 禁言, 0: 关闭， 1：开启
            + add_in_group: 1 (string, required) - 允许群内添加好友, 0: 关闭， 1：开启
            + invite: 1 (string, required) - 允许邀请人入群, 0: 关闭， 1：开启
            + invite_way: 1 (number, required) - 邀请人入群方法, 0: 关闭， 1：开启
    + Body {
        "setting": {
                "no_speaking": 0,
                "add_in_group": 1,
                "invite": 1,
                "invite_way":1
            },
    }

### 更改群设置 [POST]
+ Parameters
     + group_id: 12 (number, required) - 群id

+ Request (application/json)
    + Attributes (object)
        + key: no_speaking (string, required) - 配置项: no_speaking:禁言，add_in_group：群内添加好友，invite: 邀请人入群，invite_way: 邀请人入群方法
        + value: 1 (number, required) - 配置值, 0: 关闭，1：启用

+ Response 200 (application/json)
     + Attributes (object)


## 群角色 /groups/{group_id}/roles{?role} [/groups/{group_id}/roles{?role}]
### 获取群角色 [GET]
+ Parameters
     + group_id: 12 (number, required) - 群id
     + role: admin (string, required) - 群角色： admin

+ Response 200  (application/json)
    + Attributes (object)
        + roles: (array, required) - 群角色列表
            + roles (object)
                + user_id: 1 (number, required) - 用户id
                + role: admin (string, required) - 群角色： owner/admin/member
                + no_speaking: 1 (number, required) - 是否有禁言权力, 0: 开启，1： 关闭
                + modify_info: 1 (number, required) - 是否有修改群信息的权力, 0: 开启，1： 关闭
                + add_in_group: 1 (number, required) - 是否能设置群内添加好友的能力, 0: 开启，1： 关闭



### 设置群角色(管理员) [POST]
+ Parameters
     + group_id: 12 (number, required) - 群id

+ Request (application/json)
    + Attributes (object)
        + user_ids (array, required) - 用户id数组，
            + id : 123 (number) - 用户id
        + role: string (string, required) - 群角色： owner/admin/member

+ Response 200 (application/json)
    + Attributes (object)


## 群公告 /groups/{group_id}/notices [/groups/{group_id}/notices] 
### 获取群公告 [GET]
+ Parameters
     + group_id: 12 (number, required) - 群id
+ Response 200 (application/json)
    + Attributes (object)
        + notice_id: 12435 (number, required) - 群公告id
        + notice: hello world! (string, required) - 群公告信息
        + updated_at: 15xxxxxxxx (number, required) -  更新时间戳
        + modify_by: 12435 (number, required) - 更新者用户id

### 设置群公告 [POST]
+ Parameters
    + group_id: 12 (number, required) - 群id

+ Request (application/json)
     + Attributes (object)
        + notice: hello world! (string, required) - 群公告信息

+ Response 200 (application/json)
     + Attributes (object)


## 群请求相关 /groups/{group_id}/join_reqs [/groups/{group_id}/join_reqs]
### 申请入群 [POST]
+ Parameters
    + group_id: 12 (number, required) - 群id

+ Request (application/json)
    + Attributes (object)
        + invite_id: 2134 (number, required) - 邀请人的user_id,主动申请入群的,填申请人user_id
        + join_way: qrcode (string, required) - 加入方式: create/invite/qrcode
        + message: I'm xxx (string, required) - 添加消息

+ Response 200 (application/json)
     + Attributes (object)

## 入群申请处理相关 /groups/{group_id}/join_reqs/{req_id} [/groups/{group_id}/join_reqs/{req_id}]
### 获取入群申请 [GET]
+ Parameters
    + group_id: 12 (number, required) - 群id
    + req_id: 12 (number, required) - request id

+ Request 
     + Attributes (object)

+ Response 200 (application/json)
    + Attributes (object)
        + id: 2134 (number, required) - 邀请人的user_id,主动申请入群的,填申请人user_id
        + create_at: 15000000000000 (number, required) - 时间戳
        + group_id: 354  (number, required) - 群id
        + user_id: 2 (number, required) - 用户id
        + operator_id： 3 (number, required) - 用户id
        + join_way: qrcode (string, required) - 加入方式: create/invite/qrcode
        + status: applying (string, required) - 申请状态
        + message: I'm xxx (string, required) - 添加消息

### 审批入群申请 [POST]
+ Parameters
    + group_id: 12 (number, required) - 群id
    + req_id: 12 (number, required) - request id

+ Request 
     + Attributes (object)
        + approve： agree (string, required) - 审批： agree/reject

+ Response 200 (application/json)
    + Attributes (object)


## 资源同步 /users/{user_id}/res [/users/{user_id}/res]
### 获取同步资源集合 [GET]
+ Parameters
    + user_id: 12 (number, required) - 用户id

+ Response 200 (application/json)
     + Attributes (object)
        + contacts (object)
            + list: 1500000 (number, required) - 时间戳，上次联系人列表更新时间戳
        + groups (object)
            + list: 1500000 (number, required) - 时间戳，上次群列表更新时间戳
        + settings (object)
            + setting: 124 (number, required) - 个人设置记录id
            + chat: 124 (number, required) - 会话记录id


## 会话设置 /users/{user_id}/chat_settings{?after} [/users/{user_id}/chat_settings{?after}]
### 获取会话设置记录 [GET]
+ Parameters
    + user_id: 14 (number, required) - user id
    + after: 12445 (number, required) - 上次的会话设置记录id

+ Response 200 (application/json)
     + Attributes (object)
         + chat_settings: (array) - 会话设置记录
            + chat_setting (object)
                + object_id: 14 (number, required) - imid or group id
                + chat_type: 1 (number, required) - 会话类型， 1：单聊， 2：群聊
                + key： xxx (string, required) - 配置类型，如, top:置顶， mute:免打扰，(由客户端自定义，但要三端统一)
                + value： 0 (number, required) - 配置值，如, 1:开启， 2:关闭，(由客户端自定义，但要三端统一)


### 设置会话设置记录 [POST]
+ Parameters
    + user_id: 14 (number, required) - user id

+ Request (application/json)
     + Attributes (object)
         + object_id: 14 (number, required) - user id or group id
         + chat_type: 1 (number, required) - 会话类型， 1：单聊， 2：群聊
         + key： xxx (string, required) - 配置类型，如, top:置顶， mute:免打扰，(由客户端自定义，但要三端统一)
         + value： 0 (number, required) - 配置值，如, 1:开启， 2:关闭，(由客户端自定义，但要三端统一)

+ Response 200 (application/json)
     + Attributes (object)


## 个人设置 /users/{user_id}/settings{?after} [/users/{user_id}/settings{?after}]
### 获取个人设置 [GET]
+ Parameters
    + user_id: 14 (number, required) - user id
+ Response 200 (application/json)
     + Attributes (object)
         + settings: (array, required) - 配置列表
            + setting  (object)
                + type: 1 (number, required) - 设置类型， 如： 通用/个人/通知/隐私（由客户端自定义，但要三端统一）
                + key： xxx (string, required) - 具体设置类型 (由客户端自定义，但要三端统一)
                + value： 0 (number, required) - 配置值，如, 1:开启， 2:关闭，(由客户端自定义，但要三端统一)

### 配置个人设置 [POST]
+ Parameters
    + user_id: 14 (number, required) - user id

+ Request (application/json)
     + Attributes (object)
         + user_id: 14 (number, required) - user id
         + type: 1 (number, required) - 设置类型， 如： 通用/个人/通知/隐私（由客户端自定义，但要三端统一）
         + key： xxx (string, required) - 具体设置类型 (由客户端自定义，但要三端统一)
         + value： 0 (number, required) - 配置值，如, 1:开启， 2:关闭，(由客户端自定义，但要三端统一)

+ Response 200 (application/json)
     + Attributes (object)



## 个人设置-黑名单 /users/{user_id}/blacklist [/users/{user_id}/blacklist]
### 获取黑名单列表 [GET]
+ Parameters
    + user_id: 14 (number, required) - user id
+ Response 200 (application/json)
    + Attributes (object)
        + blacklist: (array, required) - 黑名单列表
            + blacklist (object)
                + user_id: 124 (number, required) - 被拉黑人的user_id
                + created_at: 15xxxxx (number, required) - 拉黑时间戳

### 添加黑名单 [POST]
+ Parameters
    + user_id: 14 (number, required) - user id

+ Request (application/json)
     + Attributes (object)
        + blacklist (array, required) - 被拉黑人的user_id数组
            + id : 123 (number) - 用户id

+ Response 200 (application/json)
    + Attributes (object)

### 移除黑名单 [DELETE]
+ Parameters
    + user_id: 14 (number, required) - user id

+ Request (application/json)
     + Attributes (object)
        + blacklist (array, required)  - 黑名单的user_id数组
            + id : 123 (number) - 用户id

+ Response 200 (application/json)
    + Attributes (object)


## 登录设备 /users/{user_id}/devices [/users/{user_id}/devices]
### 获取登录设备列表 [GET]
+ Parameters
    + user_id: 14 (number, required) - user id

+ Response 200 (application/json)
    + Attributes (object)
        + devices (array)
            + device (object)
                + device_id: 12 (number, required) - 设备id 
                + login_at： 1559808709 (number, required) - 最后一次登录时间
                + Name：HUAWEI (string, required) - 设备名称
                + Model: android xxx (string, required) - 设备型号信息
    + Body {
        "devices": [
            {
                "device_id": 12 ,
                "login_at": 1559808709 ,
                "Name"："HUAWEI",
                "Model" : "android ",
            }
        ]
    }

## 登录设备管理 /users/{user_id}/devices/{device_id} [/users/{user_id}/devices{device_id}]
### 修改登录设备信息 [POST]
+ Parameters
    + user_id: 14 (number, required) - user id
    + device_id: 1 (number, required) - device id

+ Request (application/json)
     + Attributes (object)
         + name: HUAWEI (string, required) - 设备名称

+ Response 200 (application/json)
    + Attributes (object)

### 删除登录设备 [DELETE]
+ Parameters
    + user_id: 14 (number, required) - user id
    + device_id: 1 (number, required) - device id

+ Response 200 (application/json)
    + Attributes (object)



## 账号 /users/{user_id}/account [/users/{user_id}/account]
###  修改用户account [POST]
+ Parameters
    + user_id: 14 (number, required) - user id
+ Request (application/json)
    + Attributes (object)
        + account_alias: derek (string, required) - 修改account
+ Response 200 (application/json)
    + Attributes (object)

## 密码 /users/{user_id}/password [/users/{user_id}/password]
###  password [POST]
+ Parameters
    + user_id: 14 (number, required) - user id
+ Request (application/json)
    + Attributes (object)
        + old_password: derek (string, required) - 救password，需要加密，加密方式由三端协商
        + new_password: derek (string, required) - 新password，需要加密
+ Response 200 (application/json)
    + Attributes (object)


## 隐私设置 /users/{user_id}/privacy_settings [/users/{user_id}/privacy_settings]
### 获取隐私设置 [GET]
+ Parameters
    + user_id: 14 (number, required) - user id
+ Response 200 (application/json)
    + Attributes (object)
        + setting: (object)
            + id: 1 (number, required) - 设置id
            + user_id: 123 (number, required) - 用户id
            + add_verify: 1 (number, required) - 添加认证， 0： 关闭， 1：启用
    + Body {
        "setting": {
            "id": 1,
            "user_id": 23,
            "add_verify": 1
        }
    }

### 修改隐私设置 [POST]
+ Parameters
    + user_id: 14 (number, required) - user id
+ Request (application/json)
    + Attributes (object)
        + key: add_verify (string, required) - 设置类型， add_verify：被添加好友是否需要验证
        + value: 0 (string, required) - 设置值， add_verify：0关闭，1启用
+ Response 200 (application/json)
    + Attributes (object)


## 推送设置 /users/{user_id}/push_settings  [/users/{user_id}/push_settings]
###  获取推送设置 [GET]
+ Parameters
    + user_id: 14 (number, required) - user id

+ Response 200 (application/json)
    + Attributes (object)
        + setting: (object)
            + switch: 0 (number, required) - 推送开关
            + detail: 0 (number, required) - 推送详情

###  设置推送 [POST]
+ Parameters
    + user_id: 14 (number, required) - user id
+ Request (application/json)
    + Attributes (object)
        + kay: detail (string, required) , - 设置类型: switch/detail
        + value: 0 (number, required) - 设置值，0关闭，1启用

+ Response 200 (application/json)
    + Attributes (object)


## 本地通讯录 /users/{user_id}/mobile_contacts{?device_id} [/users/{user_id}/mobile_contacts{?device_id}]
### 获取通讯录 [GET]
+ Parameters
    + user_id: 14 (number, required) - user id
    + device_id: kjkj (string, required) - 设备唯一id
+ Request (application/json)
    + Attributes (object)
+ Response 200 (application/json)
    + Attributes (object)
        + contacts (array) - 通讯录列表
            + contact (object) - 通讯录信息
                + cn : +86 (string, required)  - 国家号
                + phone: 10086 (string, required) - 手机号码
                + name: derek (string, required) - 通讯录备注
                + user_id: 12 (number, required) - 用户id
                + imid:1235414 (number, required) - imid
                + avatar: sdkfjalskjd (string, required) - 用户头像
                + friend_nickname: 15ajsdf (string, required) - 用户昵称
                + is_friend: 0 (boolean, required) - 是否好友


### 上传通讯录 [POST]
+ Parameters
    + user_id: 14 (number, required) - user id  
+ Request (application/json)
    + Attributes (object)
        + device_id: sdfa (string, required) - 设备唯一id
        + contacts: (array) - 通讯录列表
            + contact (object) - 通讯录信息
                + cn : +86 (string, required)  - 国家号
                + phone: 10086 (string, required) - 手机号码
                + name: derek (string, required) - 通讯录备注
+ Response 200 (application/json)
    + Attributes (object)


## 地址位置  /users/{user_id}/locations [/users/{user_id}/locations]
### 设置地理位置 [POST]
+ Parameters
    + user_id: 14 (number, required) - user id  
+ Request (application/json)
    + Attributes (object)
        + longitude: 12.35 (number, required) - 京都
        + latitude: 35.3 (number, required) - 通   
+ Response 200 (application/json)
    + Attributes (object)

### 清楚地理位置 [DELETE]
+ Parameters
    + user_id: 14 (number, required) - user id  
+ Response 200 (application/json)
    + Attributes (object)


## 附近的人 /users/{user_id}/people_nearby{?limit&dist}  [/users/{user_id}/people_nearby{?limit&dist}]
### 获取附近的人 [GET]
+ Parameters
    + user_id: 14 (number, required) - user id  
    + limit: 20 (number, required) - 每次获取数量
    + dist: 10 (number, required) - 距离，最大值:20, 单位：km

+ Response 200 (application/json)
    + Attributes (object)
        + nearby: (array, required) -  附近的人列表
            + info (object)
                + user_id: 53 (number, required) - 用户id
                + im_id: 155555 (number, required) - imid
                + nickname: derek (string, required) - nickname
                + sex: male (string, required) - 性别， 女：female， 男：male
                + avatar: 52c9a9d3a72f94ef150d8f48d0427f0d (string, required) - 用户头像
                + signature: hello (string, required) - 个性签名
                + distance: 7.8 (number, required) - 距离， 单位：km
                + zone: shenzhen (string, required) - 地址，待定