FORMAT: 1A

# WARM API（业务系统API）
此分类下的API主要是给IM客户端调用，以完成产品业务，以所也可以称为**业务系统API**，以便与**IM系统API**区分开来。**业务系统API**同时也是IM客户端连接到IM服务端的**介绍人**，因为IM客户端必须依赖**业务系统API**提供的token才能使用**IM系统API**。

## 基本信息

+ 版本：v1
+ 定义时间：2019-12-16
+ 应用时间：2019-03-16

## 基本约定

+ URL前缀：/api/v1/
+ 接口形态：Restful
+ 方法：GET/POST/PUT/DELETE
+ 返回：JSON

## HTTP请求头

+ 需要验证的操作: **Authorization：JWT jwt-token**

## http响应格式
+ Attributes (object)

    + code: 0 (number, required) -  系统状态码
    + message: error (string, required) - 错误信息 
    + data: {} (object), required) -  响应数据


+ Body
    {
        "code": 0,
        "message": "error",
        "data": {...},
    }

## http状态码定义
+ 200：GET、PUT、PATCH success
+ 201：POST success
+ 204：DELETE success
+ 400：bad request, bad param
+ 401：api unauthorized
+ 403：user forbidden
+ 404：GET not found


## 平台启动信息 /config/{platform} [/config/{platform]
### 平台启动信息 [GET]
+ Parameters
    + platform: iphone (string, required) - 平台： pc iphone android mac

+ Response  200 (application/json)
    + Attributes (object)

        + start_info:  (object, required) - 启动信息
            + start_type: picture (string, required) - 启动类型
            + picture_url: /xxx/xxx (string, required) - 启动图片地址
            + video_url: /xxx/xxx (string, required) - 启动视频地址
        + version_info: (object, required) - 版本信息
            + updated_at: 2020-01-13 13:49:00 (string, required) -  更新发布时间
            + platform:  iphone (string, required) - 平台： pc iphone android mac
            + ver: 0.0.1 (string, required) - 版本号
            + downloa_url: http://xxx.xxx.com (string, required) -  下载地址
            + upgrade_info: upgrade: 1.xxxx; (string, required) - 版本更新信息
            + is_force: true (string,required) - 是否强制更新
        + web_server: (object, required) - http服务器
            + addrs: ["1270.0.0.1:9001"] (array, required) - http服务器地址
        + file_server: (object, required) - 文件服务
            + addrs: ["1270.0.0.1:9001"] (array, required) - 文件服务地址

    + Body
        {
            "start_info": {
                "start_type": "picture",
                "picture_url": "/xxx/xxx",
                "video_url": "/xxx/xxx"
            },
            "version_info": {
                "updated_at": "2020",
                "platform": "iphone",
                "ver": "0.0.1",
                "downloa_url": "http://xxx.xxx.com",
                "upgrade_info": "upgrade: 1.xxxx;",
                "is_force": "true"
            },
            "web_server": {
                "addrs": [
                "[\"1270.0.0.1:9001\"]"
                ]
            },
            "file_server": {
                "addrs": [
                "[\"1270.0.0.1:9001\"]"
                ]
            }
        }


## SMS短信 /sms/{phone} [/sms/{phone}]
### 发送短信 [POST]
+ Parameters
    + phone: 10086 (string, required) - 手机号码

+ Request (application/json)
    + Attributes (object)
        + country_code: +86 (string, required) - 国家号
        + sms_type: vcode (string, required) - 短信类型
        + is_test: 0 (number, required) - 是否测试

+ Response 201 (application/json)
    + Attributes (object)
        + v_code: 7835 (string, required) - 验证码(测试环境才会返回验证码)
        + expire：60 (number, required) - 有效期(second)
    + Body
        {
            "v_code": "7835",
            "expire": 60,
        }


## auth /auth/ [/auth/]
### login [POST]
+ Request (application/json)
    + Attributes (object)
        + v_code: 0988 (string, optional) - 验证码
        + platform: iphone (string, required) - 设备类型：android、iphone、pc、mac
        + country_code: +86 (string, required) - 国家号
        + login_type: vcode (string, required) - 登录类型: vcode, qrcode
        + phone: 10086 (string, required) - 手机号码

+ Response 201 (application/json)
    + Attributes (object)    
        + web_server: (object, required) - http服务器
            + addrs: ["1270.0.0.1:9001"] (array, required) - http服务器地址
        + file_server: (object, required) - 文件服务器
            + addrs: ["1270.0.0.1:9001"] (array, required) - 文件服务地址
        + im_server: (object, required) - im服务器
            + addrs: ["1270.0.0.1:9001"] (array, required) - im服务地址
        + user: (object, required)
            + user_id: 
        + token: xxxxxxxxx (array, required) - token
        + exp: 60 (array, required) - token
        + im_token: xxxxxxxxx (array, required) - im token
        + im_exp: 40 (array, required) - im token exp


### logout [DELETE]
+ Response 204 (application/json)


## 二维码登陆相关 /auth/qrcode [/auth/qrcode{?qr_token}]
### 获取二维码状态（pc接口) [GET]
+ Parameters
    + qr_token: xxxx (string, required) - qrCode token
+ Response 200 (application/json)

### 获取登陆二维码信息（pc接口） [POST]

+ Request (application/json)
    + Attributes (object)
        + platform: pc (string, required) - 设备类型

+ Response 201 (application/json)

    + Attributes (object)

### app扫码登陆、 同意/取消二维码登陆 （app接口） [PATCH]
+ Request (application/json)

    + Attributes (object)

        + qr_token: xxxxx (string, required) - qr_token
        + update_type: scan_code (string, required) -  操作类型：scan_code/agree/cancel

+ Response 200 (application/json)



## 通过phone搜索联系人 /user/phone/{phone} [/users/phone/{phone}]
### 通过phone搜索联系人parameters [GET]
+ Parameters
    + phone: xxxxx (string, required) - 手机号

+ Response 200 (application/json)
    + Attributes (object)
        + users: (array, required) - 用户列表 
            + user_id: 125 (number, required) - 用户id
            + account: xxxxx (string, required) - 账号
            + account_alias: xxxxx (string, required) - 账号别名
            + im_id: 125 (number, required) - im id
            + nickname: xxxxx (string, required) - 用户昵称
            + platform: xxxxx (string, required) - 设备平台
            + country_code: xxxxx (string, required) - 国家号
            + phone: xxxxx (string, required) - 手机号
            + home_phone: xxxxx (string, required) - 座机号码
            + sex: xxxxx (string, required) - 性别: 男：male， 女：female
            + birthday: xxxxx (string, required) - 生日： 19xx-xx-xx
            + avatar: xxxxx (string, required) - /image/avatar/1.png
            + job: xxxxx (string, required) - 用户工作
            + address: xxxxx (string, required) - 用户地址
            + signature: xxxxx (string, required) - 个性签名
    
    + Body
    {
        "users": [
            {
                "user_id": 1,
                "account": "A1NSHijF6cBpudF3khcBCkfmVm",
                "account_alias": "",
                "im_id": 0,
                "nickname": "ujtb4h",
                "platform": "iphone",
                "country_code": "+86",
                "phone": "18814181870",
                "home_phone": "",
                "sex": "",
                "birthday": "",
                "avatar": "/image/avatar/5.jpeg",
                "email": "",
                "job": "",
                "address": "",
                "signature": "hello world!"
            }
        ]
    }

## 通过account搜索联系人 /user/account/{account} [/users/account/{account}]
### 通过account搜索联系人 [GET]
+ Parameters
    + account: xxxxx (string, required) - 账号

+ Response 200 (application/json)
    + Attributes (object)
        + users: (array, required) - 用户列表 
            + user_id: 125 (number, required) - 用户id
            + account: xxxxx (string, required) - 账号
            + account_alias: xxxxx (string, required) - 账号别名
            + im_id: 125 (number, required) - im id
            + nickname: xxxxx (string, required) - 用户昵称
            + platform: xxxxx (string, required) - 设备平台
            + country_code: xxxxx (string, required) - 国家号
            + phone: xxxxx (string, required) - 手机号
            + home_phone: xxxxx (string, required) - 座机号码
            + sex: xxxxx (string, required) - 性别: 男：male， 女：female
            + birthday: xxxxx (string, required) - 生日： 19xx-xx-xx
            + avatar: xxxxx (string, required) - /image/avatar/1.png
            + job: xxxxx (string, required) - 用户工作
            + address: xxxxx (string, required) - 用户地址
            + signature: xxxxx (string, required) - 个性签名
    
    + Body
    {
        "contacts": [
            {
                "user_id": 1,
                "account": "A1NSHijF6cBpudF3khcBCkfmVm",
                "account_alias": "",
                "im_id": 0,
                "nickname": "ujtb4h",
                "platform": "iphone",
                "country_code": "+86",
                "phone": "18814181870",
                "home_phone": "",
                "sex": "",
                "birthday": "",
                "avatar": "/image/avatar/5.jpeg",
                "email": "",
                "job": "",
                "address": "",
                "signature": "hello world!"
            }
        ]
    }

## 通过id搜索联系人 /user/id/{id} [/users/id/{id}]
### 通过id搜索联系人 [GET]
+ Parameters
    + id: 4524 (number, required) - 用户id

+ Response 200 (application/json)
    + Attributes (object)
        + contacts: (array, required) - 用户列表 
            + user_id: 125 (string, required) - 用户id
            + account: xxxxx (string, required) - 账号
            + account_alias: xxxxx (string, required) - 账号别名
            + im_id: 125 (string, required) - im id
            + nickname: xxxxx (string, required) - 用户昵称
            + platform: xxxxx (string, required) - 设备平台
            + country_code: xxxxx (string, required) - 国家号
            + phone: xxxxx (string, required) - 手机号
            + home_phone: xxxxx (string, required) - 座机号码
            + sex: xxxxx (string, required) - 性别: 男：male， 女：female
            + birthday: xxxxx (string, required) - 生日： 19xx-xx-xx
            + avatar: xxxxx (string, required) - /image/avatar/1.png
            + job: xxxxx (string, required) - 用户工作
            + address: xxxxx (string, required) - 用户地址
            + signature: xxxxx (string, required) - 个性签名
    
    + Body
    {
        "contacts": [
            {
                "user_id": 1,
                "account": "A1NSHijF6cBpudF3khcBCkfmVm",
                "account_alias": "",
                "im_id": 0,
                "nickname": "ujtb4h",
                "platform": "iphone",
                "country_code": "+86",
                "phone": "18814181870",
                "home_phone": "",
                "sex": "",
                "birthday": "",
                "avatar": "/image/avatar/5.jpeg",
                "email": "",
                "job": "",
                "address": "",
                "signature": "hello world!"
            }
        ]
    }


## 联系人集合 /users/{id}/contacts [/users/{id}/contacts]
### 获取所有联系人的信息 [GET]

+ Parameters
    + id: 1235 (number, required) - 用户id

+ Response  200 (application/json)

    + Attributes (object)
        + contacts: (array, required)
            + user_id: 86 (number, required) - 用户id
            + nickname: neil (string, required) - 昵称
            + friend_nickname: neil (string, required) - 用户对朋友的昵称 
            + avatar: /image/avatar/2.png (string, required) - 最后更新时间
            + im_id: 137 (number, required) - im id
            + mute_notice: yes (string, required) - 消息免打扰： yes/no. 默认：no

    + Body
        {
            "contacts": [
                {
                    "user_id": 100000135,
                    "im_id": 0,
                    "nickname": "ujtb4h",
                    "friend_nickname": "",
                    "avatar": "/image/avatar/5.jpeg",
                    "mute_notice": "no"
                },
                {
                    "user_id": 100000136,
                    "im_id": 0,
                    "nickname": "ujtb4h",
                    "friend_nickname": "",
                    "avatar": "/image/avatar/5.jpeg",
                    "mute_notice": "yes"
                },
                {
                    "user_id": 100000138,
                    "im_id": 0,
                    "nickname": "ujtb4h",
                    "friend_nickname": "",
                    "avatar": "/image/avatar/5.jpeg",
                    "mute_notice": "no"
                },
                {
                    "user_id": 100000137,
                    "im_id": 0,
                    "nickname": "ujtb4h",
                    "friend_nickname": "",
                    "avatar": "/image/avatar/5.jpeg",
                    "mute_notice": "no"
                }
            ]
        }

## 联系人信息 /users/{id}/contacts/{cid}  [/users/{id}/contacts/{cid}]
### 获取单个联系人信息 [GET]
+ Parameters
    + id: 1235 (number, required) - 用户id
    + cid: 1235 (number, required) - 联系人id

+ Response  200 (application/json)

    + Attributes (object)
        + user_id: 125 (string, required) - 用户id
        + account: xxxxx (string, required) - 账号
        + account_alias: xxxxx (string, required) - 账号别名
        + im_id: 125 (string, required) - im id
        + nickname: xxxxx (string, required) - 用户昵称
        + platform: xxxxx (string, required) - 设备平台
        + country_code: xxxxx (string, required) - 国家号
        + phone: xxxxx (string, required) - 手机号
        + home_phone: xxxxx (string, required) - 座机号码
        + sex: xxxxx (string, required) - 性别: 男：male， 女：female
        + birthday: xxxxx (string, required) - 生日： 19xx-xx-xx
        + avatar: xxxxx (string, required) - /image/avatar/1.png
        + job: xxxxx (string, required) - 用户工作
        + address: xxxxx (string, required) - 用户地址
        + signature: xxxxx (string, required) - 个性签名
        + is_friend: true (string , required) - 是否是朋友，布尔值
        + is_delete: false (string , required) - 是否是朋友，布尔值
        + is_black: false (string , required) - 是否是朋友，布尔值
        + friend_nickname: derek (string, required) - 对朋友的昵称
        + mute_notice: yes (string, required) - 消息免打扰： yes/no

### 添加联系人,同意/拒绝添加联系人 [POST]
+ Parameters
    + id: 1235 (number, required) - 用户id
    + cid: 1235 (number, required) - 联系人id

+ Request (application/json)

    + Attributes (object)
        + handle_type: add (string, required) - 处理类型：add/agree/reject
        + add_by: share (string, optional) - 通过什么方式添加朋友：share/qrcode/phone/account
        + message: I'm xx (string, optional) - 添加朋友时的备注
        + friend_im_id: 243 (number, required) - 联系人imid

+ Response  201 (application/json)

    + Attributes (object)

### 修改联系人信息 [PATCH]
+ Parameters
    + id: 1235 (number, required) - 用户id
    + cid: 1235 (number, required) - 联系人id

+ Request (application/json)

    + Attributes (object)
        + nickname: derek (string, required) - 用户昵称
        + mute_notice: yes (string, required) - 消息免打扰： yes/no


+ Response  200 (application/json)


### 删除联系人 [DELETE]
+ Parameters
    + id: 1235 (number, required) - 用户id
    + cid: 1235 (number, required) - 联系人id

+ Response  204 (application/json)


## 个人中心 /users/{id} [/users/{id}]
### 获取个人中心信息 [GET]
+ Parameters
    + id: 1235 (number, required) - 用户id 

+ Response  200 (application/json)

    + Attributes (object)
        + user_id: 125 (string, required) - 用户id
        + account: xxxxx (string, required) - 账号
        + account_alias: xxxxx (string, required) - 账号别名
        + im_id: 125 (string, required) - im id
        + nickname: xxxxx (string, required) - 用户昵称
        + platform: xxxxx (string, required) - 设备平台
        + country_code: xxxxx (string, required) - 国家号
        + phone: xxxxx (string, required) - 手机号
        + home_phone: xxxxx (string, required) - 座机号码
        + sex: xxxxx (string, required) - 性别: 男：male， 女：female
        + birthday: xxxxx (string, required) - 生日： 19xx-xx-xx
        + avatar: xxxxx (string, required) - /image/avatar/1.png
        + job: xxxxx (string, required) - 用户工作
        + address: xxxxx (string, required) - 用户地址
        + signature: xxxxx (string, required) - 个性签名

### 修改个人中心信息 [POST]
+ Parameters
    + id: 1235 (number, required) - 用户id

+ Attributes (object)
    + nickname: derek (string, required) - 要修改的昵称

+ Response  200 (application/json)


## 当前用户 /user/me [/user/me]
### （旧的）修改当前用户信息 [POST]
+ Request
    + Attributes (object)
        + modify_type: nickname (string, required) - 修改类型: nickname
        + value: meme (string, required) - 修改值

+ Response 200 (application/json)

## 文件上传 /files [/files]
### 上传文件 [POST]
form的命名统一为file
+ Headers:

    + file: name.txt (string, required) - 文件名
    + content-type: multipart/form-data; (string, required) - 内容类型

+ Response 200 (application/json)

    + file_token: asdfasdgagas (string, required) - 文件token


## 下载文件 /files/{file_token} [/files/{file_token}]
### 下载文件 [GET]
+ Parameters
    + file_token: werutipoiqeutoijqoeij (string, required) - 文件token

+ Response 200 (application/json)

    + Attributes (object)

        + data: lkajslkdjfla (string, required) - 文件数据


## 群相关操作 /groups [/groups]
### 创建群（Y） [POST]

+ Request (application/json)

    + Attributes (object)

        + name: my group (string, required) - 群名称
        + group_type: chat (string, optional) - 群类型
        + max_cap: 100 (number, optional) - 群成员容量，默认200
        + notice: hello world! (string, optional) - 群通告

+ Response 200 (application/json)

    + Attributes (object)
        + group_id: 123 (number, required) - 群id
        + name: my group (string, required) - 群名称
        + group_type: chat (string, required) - 群类型
        + max_cap: 100 (number, required) - 群成员容量，默认200
        + member_hash: lkajslkdjfla (string, required) - 成员hash： 所有群成员的id按升序排列，合并成一个字符串，再计算该字符串的md5
        + created_at: 15xxxxx (number,required) - 建群时间
        + owner_id: 1 (number, required) - 群主的用户id
        + creator_id: 1 (number, required) - 建群者的用户id
        + avatar: /image/avatar/2.png (string, required) - 群头像，暂时先分配默认头像
        + notice: hello world! (string, required) - 群通告

### 获取群列表(Y) [GET]

+ Response 200 (application/json)

    + Attributes (object)
        + group_id: 123 (number, required) - 群id
        + name: my group (string, required) - 群名称
        + avatar: /image/avatar/2.png (string, required) - 群头像，默认空值
        + count: 1 (number, required) - 群成员人数
        + role： owner (string, required) - 群角色： owner/admin/member
        + mute_notice: yes (string, required) - 消息免打扰： yes/no

## 获取群信息 /groups/{group_id}/info [/groups/{group_id}/info]
### 获取群概要信息(Y)  [GET]
+ Parameters
    + group_id: 1235 (number, required) - 群id

+ Response 200 (application/json)

    + Attributes (object)
        + group_id: 123 (number, required) - 群id
        + name: my group (string, required) - 群名称
        + group_type: chat (string, required) - 群类型
        + max_cap: 100 (number, required) - 群成员容量，默认200
        + member_hash: lkajslkdjfla (string, required) - 成员hash
        + created_at: 15xxxxx (number,required) - 建群时间
        + owner_id: 1 (number, required) - 群主的用户id
        + creator_id: 1 (number, required) - 建群者的用户id
        + avatar: /image/avatar/2.png (string, required) - 群头像，暂时先分配默认头像
        + notice: hello world! (string, required) - 群通告


## 群操作 /groups/{group_id} [/groups/{group_id}]
### 获取完整群信息(Y)  [GET]
+ Parameters
    + group_id: 1235 (number, required) - 群id

+ Response 200 (application/json)

    + Attributes (object)
        + info (object)
            + group_id: 123 (number, required) - 群id
            + name: my group (string, required) - 群名称
            + group_type: chat (string, required) - 群类型
            + max_cap: 100 (number, required) - 群成员容量，默认200
            + member_hash: lkajslkdjfla (string, required) - 成员hash
            + created_at: 15xxxxx (number,required) - 建群时间
            + owner_id: 1 (number, required) - 群主的用户id
            + creator_id: 1 (number, required) - 建群者的用户id
            + avatar: /image/avatar/2.png (string, required) - 群头像，暂时先分配默认头像
            + notice: hello world! (string, required) - 群通告
        + members:  (array, require) - 成员列表
           + group_nickname: derek (string, required) - 用户昵称
           + user_id: 123 (number, required) - 用户id
           + imid: 1241235 (number, required) - imid
           + avatar: /image/avatar/2.png  (string, required) - 用户头像
           + role: owner (string, required) - 用户群角色

### 修改群信息(Y)  [POST]
+ Request (application/json)
    + Attributes (object)
        + name: my group (string, optional) - 群名称
        + owner_id: 1 (number, optional) - 群主的用户id
        + max_cap: 100 (number, optional) - 群成员容量，默认200
        + avatar: /image/avatar/2.png (string, optional) - 群头像，暂时先分配默认头像
        + notice: hello world! (string, optional) - 群通告

+ Response 200 (application/json)
    + Attributes (object)

### 解散群(Y)  [DELETE]
+ Parameters
    + group_id: 1235 (number, required) - 群id

+ Response 200 (application/json)
     + Attributes (object)


## 群成员 /groups/{group_id}/members [/groups/{group_id}/members]
### 获取群成员列表(Y) [GET]
+ Parameters
    + group_id: 1235 (number, required) - 群id

+ Response 200 (application/json)
    + Attributes (object)
        + member_hash: asldkjflaksjdfl (string, required) - 群成员hash
        + members: (array, require) - 数组
            + group_nickname: derek (string, required) - 用户昵称
            + user_id: 123 (number, required) - 用户id
            + imid: 1241235 (number, required) - imid
            + avatar: /image/avatar/2.png  (string, required) - 用户头像
            + role: owner (string, required) - 用户群角色

### 添加群成员(Y) [POST]
+ Parameters
    + group_id: 1235 (number, required) - 群id

+ Request (application/json)
    + Attributes (object)
        + user_ids: 123,23534 (array,required) - 用户id数组


+ Response 200 (application/json)
    + Attributes (object)

### 移除群成员(Y) [DELETE]
+ Parameters
    + group_id: 1235 (number, required) - 群id

+ Request (application/json)
    + Attributes (object)
        + user_ids: 123, 23534 (array, required) - 用户id数组

+ Response 200 (application/json)
    + Attributes (object)

## 群成员 /groups/{group_id}/members/{user_id} [/groups/{group_id}/members/{user_id}]
### 获取群成员信息(Y) [GET]
+ Parameters
    + group_id: 12 (number, required) - 群id
    + user_id: 1235 (number, required) - 用户id

+ Response 200 (application/json)
    + Attributes (object)
        + user_id: 125 (string, required) - 用户id
        + account: xxxxx (string, required) - 账号
        + account_alias: xxxxx (string, required) - 账号别名
        + im_id: 125 (string, required) - im id
        + nickname: xxxxx (string, required) - 用户昵称
        + platform: xxxxx (string, required) - 设备平台
        + country_code: xxxxx (string, required) - 国家号
        + phone: xxxxx (string, required) - 手机号
        + home_phone: xxxxx (string, required) - 座机号码
        + sex: xxxxx (string, required) - 性别: 男：male， 女：female
        + birthday: xxxxx (string, required) - 生日： 19xx-xx-xx
        + avatar: xxxxx (string, required) - /image/avatar/1.png
        + job: xxxxx (string, required) - 用户工作
        + address: xxxxx (string, required) - 用户地址
        + signature: xxxxx (string, required) - 个性签名
        + role: owner (string, required) - 群角色
        + group_nickname: derek (string, required) - 群昵称

### 修改群成员信息或设置(Y) [POST]
+ Parameters
    + group_id: 12 (number, required) - 群id
    + user_id: 1235 (number, required) - 用户id

+ Request (application/json)
    + Attributes (object)
        + group_nickname: derek (string, required) - 群成员的昵称
        + mute_notice: yes (string, required) - 消息免打扰: yes/no

+ Response 200 (application/json)
    + Attributes (object)

### 群成员退群(Y) [DELETE]
+ Parameters
    + group_id: 12 (number, required) - 群id
    + user_id: 1235 (number, required) - 用户id

+ Response (application/json)
    + Attributes (object)

## 群请求相关 /groups/{group_id}/join_reqs [/groups/{group_id}/join_reqs]
### 申请入群 [POST]
+ Parameters
    + group_id: 12 (number, required) - 群id

+ Request (application/json)
    + Attributes (object)
        + join_way: qrcode (string, required) - 加入方式: create/invite/qrcode
        + message: I'm xxx (string, required) - 添加消息

+ Response 200 (application/json)
     + Attributes (object)

## 资源同步 /res [/res]
### 获取同步资源集合 [GET]

+ Response 200 (application/json)
     + Attributes (object)
        + contacts  (object)
            + last: 15xxxxx (number, required) - 时间戳，上次联系人列表更新时间
        + groups  (object)
            + last: 15xxxxx (number, required) - 时间戳，上次群列表更新时间

## 同步联系人资源 /res/contacts/last [/res/contacts/last?after]
## 拉取联系人资源 [GET]
+ Parameters
    + after: 15xxxxxx (number, required) - 时间戳，客户端本地保存的，联系人列表上次的更新时间

+ Response 200 (application/json)
     + Attributes (object)
        + count: 3 (number, required) - 新增资源数量
        + contacts： (array, required) - 新增的联系人列表信息
            + user_id: 86 (number, required) - 用户id
            + nickname: neil (string, required) - 昵称
            + friend_nickname: neil (string, required) - 用户对朋友的昵称
            + avatar: /image/avatar/2.png (string, required) - 最后更新时间
            + im_id: 137 (number, required) - im id

## 同步群列表资源 /res/groups/last [/res/groups/last?after]
### 拉取群列表资源 [GET]
+ Parameters
    + after: 15xxxxxx (number, required) - 时间戳，客户端本地保存的，群列表上次的更新时间

+ Response 200 (application/json)
     + Attributes (object)
        + count: 3 (number, required) - 新增资源数量
        + groups： (array, required) - 新增的群列表信息
            + group_id: 123 (number, required) - 群id
            + name: my group (string, required) - 群名称
            + avatar: /image/avatar/2.png (string, required) - 群头像，默认空值
            + count: 1 (number, required) - 群成员人数
            + role： owner (string, required) - 群角色： owner/admin/member


## 会话设置 /users/{user_id}/chat_settings{?after} [/users/{user_id}/chat_settings{?after}]
### 获取会话设置记录 [GET]
+ Parameters
    + user_id: 14 (number, required) - user id
    + after: 12445 (number, required) - 上次的会话设置记录id

+ Response 200 (application/json)
     + Attributes (object)
         + chat_settings: (array) - 会话设置记录
             + object_id: 14 (number, required) - user id or group id
             + chat_type: 1 (number, required) - 会话类型， 1：单聊， 2：群聊
             + key： xxx (string, required) - 配置类型，如, top:置顶， mute:免打扰，(由客户端自定义，但要三端统一)
             + value： 0 (number, required) - 配置值，如, 1:开启， 2:关闭，(由客户端自定义，但要三端统一)


### 设置会话设置记录 [POST]
+ Parameters
    + user_id: 14 (number, required) - user id

+ Request (application/json)
     + Attributes (object)
         + object_id: 14 (number, required) - user id or group id
         + chat_type: 1 (number, required) - 会话类型， 1：单聊， 2：群聊
         + key： xxx (string, required) - 配置类型，如, top:置顶， mute:免打扰，(由客户端自定义，但要三端统一)
         + value： 0 (number, required) - 配置值，如, 1:开启， 2:关闭，(由客户端自定义，但要三端统一)

+ Response 200 (application/json)
     + Attributes (object)


## 个人设置 /users/{user_id}/settings{?after} [/users/{user_id}/settings{?after}]
### 获取个人设置 [GET]
+ Parameters
    + user_id: 14 (number, required) - user id
+ Response 200 (application/json)
     + Attributes (object)
         + settings: (array, required) - 配置列表
             + type: 1 (number, required) - 设置类型， 如： 通用/个人/通知/隐私（由客户端自定义，但要三端统一）
             + key： xxx (string, required) - 具体设置类型 (由客户端自定义，但要三端统一)
             + value： 0 (number, required) - 配置值，如, 1:开启， 2:关闭，(由客户端自定义，但要三端统一)

### 配置个人设置 [POST]
+ Parameters
    + user_id: 14 (number, required) - user id

+ Request (application/json)
     + Attributes (object)
         + user_id: 14 (number, required) - user id
         + chat_type: 1 (number, required) - 设置类型， 如： 通用/个人/通知/隐私（由客户端自定义，但要三端统一）
         + key： xxx (string, required) - 具体设置类型 (由客户端自定义，但要三端统一)
         + value： 0 (number, required) - 配置值，如, 1:开启， 2:关闭，(由客户端自定义，但要三端统一)

+ Response 200 (application/json)
     + Attributes (object)